// This file contains the seed data for initializing the database
// You can use this data to populate your Supabase tables via the Supabase UI

export const seedProducts = [
  {
    id: 'hercules',
    series: 'Hercules',
    technology: 'electrical',
    duty: 'heavy',
    ip: 'IP56',
    actions: ['momentary', 'maintained'],
    material: 'Cast Iron',
    description: 'The ultimate heavy-duty industrial footswitch.',
    applications: ['industrial', 'automotive', 'woodworking', 'general'],
    features: ['shield'], // Has full shield guard
    flagship: true,
    image: 'https://linemaster.com/wp-content/uploads/2025/04/hercules-full-shield.png',
    link: 'https://linemaster.com/product/167/hercules-full-shield/',
  },
  {
    id: 'atlas',
    series: 'Atlas',
    technology: 'electrical',
    duty: 'heavy',
    ip: 'IP68',
    actions: ['momentary'],
    material: 'Cast Aluminum',
    description: 'Fully sealed IP68 heavy-duty switch.',
    applications: ['industrial', 'automotive'],
    features: ['shield'], // Has full shield guard
    flagship: false,
    image: 'https://linemaster.com/wp-content/uploads/2025/04/atlas.png',
    link: 'https://linemaster.com/product/77/atlas-full-shield/',
  },
  {
    id: 'clipper',
    series: 'Clipper',
    technology: 'electrical',
    duty: 'medium',
    ip: 'IP20',
    actions: ['momentary', 'maintained'],
    material: 'Cast Iron',
    description: 'The industry standard. Classic cast iron.',
    applications: ['industrial', 'woodworking', 'automotive', 'general'],
    features: ['twin'], // Clipper duo image suggests twin pedal version available
    flagship: true,
    image: 'https://linemaster.com/cdn/images/products/115/115-a-shadow@1200.png',
    link: 'https://linemaster.com/product/115/clipper-single-momentary/',
  },
  {
    id: 'classic-iv',
    series: 'Classic IV',
    technology: 'electrical',
    duty: 'medium',
    ip: 'IP68',
    actions: ['momentary'],
    material: 'Cast Aluminum',
    description: 'Watertight cast aluminum. IP68 sealed.',
    applications: ['industrial', 'automotive'],
    features: [], // No special features
    flagship: false,
    image: 'https://linemaster.com/cdn/images/products/110/110-a-shadow@1200.png',
    link: 'https://linemaster.com/product/112/classic-iv/',
  },
  {
    id: 'dolphin',
    series: 'Dolphin',
    technology: 'electrical',
    duty: 'light',
    ip: 'IP20',
    actions: ['momentary'],
    material: 'Polymeric',
    description: 'Omni-directional. Popular for tattoo artists.',
    applications: ['general', 'tattoo', 'medical'],
    features: [], // No special features (omni-directional is inherent design)
    flagship: false,
    image: 'https://linemaster.com/wp-content/uploads/2025/04/dolphin-2.png',
    link: 'https://linemaster.com/product/129/dolphin/',
  },
  {
    id: 'gem-v',
    series: 'Gem-V',
    technology: 'electrical',
    duty: 'light',
    ip: 'IP20',
    actions: ['momentary'],
    material: 'Cast Zinc',
    description: 'Round omni-directional design.',
    applications: ['general', 'tattoo', 'medical'],
    features: [], // No special features
    flagship: false,
    image: 'https://linemaster.com/wp-content/uploads/2025/04/gem.png',
    link: 'https://linemaster.com/product/162/gem-v/',
  },
  {
    id: 'varior',
    series: 'Varior',
    technology: 'electrical',
    duty: 'light',
    ip: 'IP20',
    actions: ['variable'],
    material: 'Formed Steel',
    description: 'Foot-operated potentiometer for variable speed.',
    applications: ['industrial', 'automotive', 'woodworking', 'general'],
    features: [], // Variable speed is an action, not a feature
    flagship: false,
    image: 'https://linemaster.com/wp-content/uploads/2025/04/varior-potentiometer.png',
    link: 'https://linemaster.com/product/407/varior-potentiometer/',
  },
  {
    id: 'wireless-hercules',
    series: 'RF Wireless Hercules',
    technology: 'wireless',
    duty: 'heavy',
    ip: 'IP68',
    actions: ['momentary'],
    material: 'Cast Iron',
    description: 'RF Wireless. Eliminates trip hazards.',
    applications: ['industrial', 'automotive', 'medical', 'general'],
    features: ['shield'], // Hercules with shield
    flagship: true,
    image: 'https://linemaster.com/wp-content/uploads/2025/04/rf-hercules.png',
    link: 'https://linemaster.com/product/475/radio-frequency-wireless-hercules/',
  },
  {
    id: 'air-seal',
    series: 'Air Seal',
    technology: 'pneumatic',
    duty: 'light',
    ip: 'IP20',
    actions: ['momentary', 'maintained'],
    material: 'Formed Steel',
    description: 'Air-actuated electrical switch.',
    applications: ['industrial', 'general', 'medical'],
    features: [], // No special features
    flagship: false,
    image: 'https://linemaster.com/wp-content/uploads/2025/03/air_seal.png',
    link: 'https://linemaster.com/product/2/air-seal-maintained/',
  },
  {
    id: 'airval-hercules',
    series: 'Airval Hercules',
    technology: 'pneumatic',
    duty: 'heavy',
    ip: 'IP20',
    actions: ['momentary', 'maintained', 'variable'],
    material: 'Cast Iron',
    description: 'Heavy-duty cast iron pneumatic control.',
    applications: ['industrial', 'automotive'],
    features: ['shield', 'twin'], // Hercules with shield, image shows duo version
    flagship: false,
    image: 'https://linemaster.com/wp-content/uploads/2025/03/airval-hercules-duo_optimized.png',
    link: 'https://linemaster.com/product/17/airval-hercules-full-shield/',
  },
];

export const seedOptions = [
  // Application Options
  {
    id: 'app-industrial',
    category: 'application',
    value: 'industrial',
    label: 'Industrial & Manufacturing',
    description: 'Heavy machinery, CNC, assembly',
    icon: 'Factory',
    sort_order: 1,
  },
  {
    id: 'app-automotive',
    category: 'application',
    value: 'automotive',
    label: 'Automotive & Repair',
    description: 'Lifts, paint booths, tire changers',
    icon: 'Car',
    sort_order: 2,
  },
  {
    id: 'app-medical',
    category: 'application',
    value: 'medical',
    label: 'Medical & Healthcare',
    description: 'Surgical, diagnostic, patient care',
    icon: 'Heart',
    is_medical: true,
    sort_order: 3,
  },
  {
    id: 'app-woodworking',
    category: 'application',
    value: 'woodworking',
    label: 'Woodworking',
    description: 'Saws, lathes, routers',
    icon: 'Hammer',
    sort_order: 4,
  },
  {
    id: 'app-tattoo',
    category: 'application',
    value: 'tattoo',
    label: 'Tattoo & Body Art',
    description: 'Precision control for artists',
    icon: 'Palette',
    sort_order: 5,
  },
  {
    id: 'app-general',
    category: 'application',
    value: 'general',
    label: 'General / Other',
    description: 'Office, consumer, specialty',
    icon: 'Coffee',
    sort_order: 6,
  },

  // Technology Options
  {
    id: 'tech-electrical',
    category: 'technology',
    value: 'electrical',
    label: 'Electrical',
    description: 'Standard wired connection.',
    icon: 'Zap',
    available_for: ['industrial', 'automotive', 'woodworking', 'tattoo', 'general'],
    sort_order: 1,
  },
  {
    id: 'tech-pneumatic',
    category: 'technology',
    value: 'pneumatic',
    label: 'Pneumatic (Air)',
    description: 'Uses compressed air.',
    icon: 'Wind',
    available_for: ['industrial', 'automotive', 'woodworking', 'general'],
    sort_order: 2,
  },
  {
    id: 'tech-wireless',
    category: 'technology',
    value: 'wireless',
    label: 'RF Wireless',
    description: 'Cord-free operation.',
    icon: 'Radio',
    available_for: ['industrial', 'automotive', 'general'],
    sort_order: 3,
  },

  // Action Type Options
  {
    id: 'action-momentary',
    category: 'action',
    value: 'momentary',
    label: 'Momentary',
    description: 'Active while pressed.',
    icon: 'CircleDot',
    available_for: ['electrical', 'pneumatic', 'wireless'],
    sort_order: 1,
  },
  {
    id: 'action-maintained',
    category: 'action',
    value: 'maintained',
    label: 'Maintained',
    description: 'Press ON, press again OFF.',
    icon: 'ToggleLeft',
    available_for: ['electrical', 'pneumatic'],
    sort_order: 2,
  },
  {
    id: 'action-variable',
    category: 'action',
    value: 'variable',
    label: 'Variable Speed',
    description: 'Speed varies with pressure.',
    icon: 'Gauge',
    available_for: ['electrical', 'pneumatic'],
    sort_order: 3,
  },

  // Environment Options
  {
    id: 'env-dry',
    category: 'environment',
    value: 'dry',
    label: 'Dry / Indoor',
    description: 'IP20 sufficient.',
    icon: 'Home',
    sort_order: 1,
  },
  {
    id: 'env-damp',
    category: 'environment',
    value: 'damp',
    label: 'Damp / Splash',
    description: 'IP56 recommended.',
    icon: 'CloudRain',
    sort_order: 2,
  },
  {
    id: 'env-wet',
    category: 'environment',
    value: 'wet',
    label: 'Wet / Washdown',
    description: 'IP68 required.',
    icon: 'Droplets',
    sort_order: 3,
  },

  // Feature Options
  {
    id: 'feature-shield',
    category: 'feature',
    value: 'shield',
    label: 'Safety Guard/Shield',
    description: 'Prevents accidental activation.',
    icon: 'Shield',
    sort_order: 1,
  },
  {
    id: 'feature-multi-stage',
    category: 'feature',
    value: 'multi_stage',
    label: 'Multi-Stage',
    description: '2 or 3 actuation points.',
    icon: 'Layers',
    sort_order: 2,
  },
  {
    id: 'feature-twin',
    category: 'feature',
    value: 'twin',
    label: 'Twin Pedal',
    description: 'Two independent pedals.',
    icon: 'Copy',
    sort_order: 3,
  },
  {
    id: 'feature-custom-cable',
    category: 'feature',
    value: 'custom_cable',
    label: 'Custom Cable Length',
    description: 'Non-standard cord length.',
    icon: 'Cable',
    hide_for: ['wireless', 'pneumatic'],
    sort_order: 4,
  },
  {
    id: 'feature-custom-connector',
    category: 'feature',
    value: 'custom_connector',
    label: 'Custom Connector',
    description: 'Specific plug type.',
    icon: 'Plug',
    sort_order: 5,
  },

  // Console Style Options (Medical Flow)
  {
    id: 'console-aero',
    category: 'console_style',
    value: 'aero',
    label: 'Aero Channel',
    description: 'Low-profile, streamlined design.',
    icon: 'Boxes',
    sort_order: 1,
  },
  {
    id: 'console-custom',
    category: 'console_style',
    value: 'custom',
    label: 'Custom Design',
    description: 'Unique housing tailored to your needs.',
    icon: 'Settings',
    sort_order: 2,
  },

  // Pedal Count Options (Medical Flow)
  {
    id: 'pedal-1',
    category: 'pedal_count',
    value: '1',
    label: 'Single',
    description: 'One function',
    icon: 'Circle',
    sort_order: 1,
  },
  {
    id: 'pedal-2',
    category: 'pedal_count',
    value: '2',
    label: 'Dual',
    description: 'Two functions',
    icon: 'CircleDot',
    sort_order: 2,
  },
  {
    id: 'pedal-3',
    category: 'pedal_count',
    value: '3',
    label: 'Triple',
    description: 'Three functions',
    icon: 'Target',
    sort_order: 3,
  },
  {
    id: 'pedal-4plus',
    category: 'pedal_count',
    value: '4+',
    label: 'Multi',
    description: '4+ controls',
    icon: 'Grid3x3',
    sort_order: 4,
  },

  // Medical Technical Features
  {
    id: 'med-feature-wireless',
    category: 'medical_feature',
    value: 'wireless',
    label: 'RF Wireless',
    description: 'No cords in the OR.',
    icon: 'Radio',
    sort_order: 1,
  },
  {
    id: 'med-feature-linear',
    category: 'medical_feature',
    value: 'linear',
    label: 'Variable Speed',
    description: 'Proportional control.',
    icon: 'Gauge',
    sort_order: 2,
  },
  {
    id: 'med-feature-sealed',
    category: 'medical_feature',
    value: 'sealed',
    label: 'Sealed / Washdown',
    description: 'IP68 for sterilization.',
    icon: 'Droplets',
    sort_order: 3,
  },

  // Accessory Options (Medical Flow)
  {
    id: 'acc-toe-loops',
    category: 'accessory',
    value: 'toe_loops',
    label: 'Toe Loops',
    description: 'Secure foot positioning.',
    icon: 'Circle',
    sort_order: 1,
  },
  {
    id: 'acc-guards',
    category: 'accessory',
    value: 'guards',
    label: 'Pedal Guards',
    description: 'Prevent accidental activation.',
    icon: 'Shield',
    sort_order: 2,
  },
  {
    id: 'acc-labels',
    category: 'accessory',
    value: 'labels',
    label: 'Custom Labels/Marking',
    description: 'Branding or identification.',
    icon: 'Tag',
    sort_order: 3,
  },
  {
    id: 'acc-color',
    category: 'accessory',
    value: 'color',
    label: 'Custom Color',
    description: 'Match your device.',
    icon: 'Palette',
    sort_order: 4,
  },
];