/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dhaqigiwkmsjrchrbllu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoYXFpZ2l3a21zanJjaHJibGx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4MTYxNTIsImV4cCI6MjA4NDM5MjE1Mn0.0ktzelG2dZzV-36Qz_RbPoUk59TGeLksedQD-xMLH3Q"